name: client-deploy

on:
  push:
    paths:
      - "frontend/**"
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source code.
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
        working-directory: ./frontend
      - name: Generate Environment Variables File
        run: |
          echo "REACT_APP_HOST=${{ secrets.REACT_APP_HOST }}" >> frontend/.env
          echo "REACT_APP_KAKAO_KEY=${{ secrets.REACT_APP_KAKAO_KEY }}" >> frontend/.env
          echo "REACT_APP_GEOCODER_KEY=${{ secrets.REACT_APP_GEOCODER_KEY }}" >> frontend/.env
          echo "REACT_APP_WS_HOST=${{ secrets.REACT_APP_WS_HOST }}" >> frontend/.env
          echo "REACT_APP_WS_HOST_DEV=${{ secrets.REACT_APP_WS_HOST_DEV }}" >> frontend/.env
          echo "WDS_SOCKET_PORT=${{ secrets.REACT_APP_WDS_SOCKET_PORT }}" >> frontend/.env
      - name: Build
        run: npm run build
        env:
          CI: false
        working-directory: ./frontend
      - name: SHOW AWS CLI VERSION
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_CLIENT_S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_CLIENT_S3_SECRET_ACCESS_KEY }}
          AWS_EC2_METADATA_DISABLED: true
        run: |
          aws --version
      - name: Sync Bucket
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_CLIENT_S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_CLIENT_S3_SECRET_ACCESS_KEY }}
          AWS_EC2_METADATA_DISABLED: true
        run: |
          aws s3 sync \
            --region ap-northeast-2 \
            build s3://dongnebook-bucket \
            --delete
        working-directory: ./frontend
