# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Test After PR & push

on:
  pull_request:
    paths: [ 'backend/**', '.github/workflows/gradle.yml', '.github/workflows/testBeforeMerge.yml' ]
    branches: [ 'main' , 'dev' ]

permissions: write-all


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: ./backend/
        
      - name: Test with Gradle
        run: ./gradlew test --stacktrace
        working-directory: ./backend/

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: ./backend/build/test-results/**/*.xml

      - name: Jacoco Report
        uses: madrapps/jacoco-report@v1.2
        if: always()
        with:
          title: Test Coverage Report
          paths: ./backend/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 50
          